### ISSUE TITLE
Request method for /serviceValidate

### ISSUE THREAD

**Issue by marceldegraaf** [locaweb/elixir-cassette#1]
In this library (and in your `cassette` Ruby gem) you use an HTTP POST for the request to the CAS server's `/serviceValidate` endpoint ([here](https://github.com/locaweb/elixir-cassette/blob/master/lib/cassette/client/validate_ticket.ex#L18)).

Is there a specific reason you use POST there? The CAS server we use (Casino) only [supports GET for this endpoint](https://github.com/rbCAS/CASino/blob/master/config/routes.rb#L17).

For that reason, any `Cassette.validate/2` call now results in a `{:error, :unknown}` for us, against our CAS server.

What do you think we could do? Or am I missing something?

**Comment by rhruiz** [comment]
@marceldegraaf no specific reason, I am changing it to `GET`

**Comment by rhruiz** [comment]
There you go https://hex.pm/packages/cassette/1.2.6

**Comment by marceldegraaf** [comment]
Awesome, thanks!
